// <auto-generated />
using System;
using Assignment_Chsarp5_datntph19899._1_DataProcessing._3_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_Chsarp5_datntph19899.Migrations
{
    [DbContext(typeof(Assignment_Context))]
    [Migration("20230511134457_demo6")]
    partial class demo6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Bill", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.BillDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BillID");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ID");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Combo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Coupons", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComboID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Coupon_Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discount_Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Maximum_Discount_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Minimum_Spend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Update_At")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(526)
                        .HasColumnType("nvarchar(526)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Order", b =>
                {
                    b.Property<Guid>("OrdelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdelID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.OrderDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrdelDetail");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Reviews", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("UsersID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(526)
                        .HasColumnType("nvarchar(526)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(526)
                        .HasColumnType("nvarchar(526)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("IDRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ID");

                    b.HasIndex("IDRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComboCoupons", b =>
                {
                    b.Property<Guid>("ComboID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CouponsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ComboID", "CouponsID");

                    b.HasIndex("CouponsID");

                    b.ToTable("ComboCoupons");
                });

            modelBuilder.Entity("CouponsFood", b =>
                {
                    b.Property<Guid>("CouponsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CouponsID", "FoodID");

                    b.HasIndex("FoodID");

                    b.ToTable("CouponsFood");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Bill", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", "Users")
                        .WithMany("Bills")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.BillDetail", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", "Food")
                        .WithMany("BillDetails")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Combo", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Category", null)
                        .WithMany("combos")
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Category", "Category")
                        .WithMany("Food")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Combo", "Combo")
                        .WithMany("Food")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Order", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", "Users")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.OrderDetail", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", "Food")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Reviews", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", "Users")
                        .WithMany("Reviews")
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IDRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ComboCoupons", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Combo", null)
                        .WithMany()
                        .HasForeignKey("ComboID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Coupons", null)
                        .WithMany()
                        .HasForeignKey("CouponsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CouponsFood", b =>
                {
                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Coupons", null)
                        .WithMany()
                        .HasForeignKey("CouponsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Category", b =>
                {
                    b.Navigation("Food");

                    b.Navigation("combos");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Combo", b =>
                {
                    b.Navigation("Food");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Food", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Assignment_Chsarp5_datntph19899._1_DataProcessing._1_Models.Users", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
